"use client";

import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import LoadingOverlay from "@/components/LoadingOverlay";
import styles from "./page.module.css";

// Dummy feed items simulating a massive community platform
const EXPLORE_FEED = [
  { id: 1, image: "/catalog/hoodie.png", author: "@fashionista_22", likes: "1.2k" },
  { id: 2, image: "/catalog/blazer.png", author: "@corp_goth", likes: "840" },
  { id: 3, image: "/catalog/casual-shirt.png", author: "@weekend_vibes", likes: "2.1k" },
  { id: 4, image: "/catalog/kurta.png", author: "@ethnic_daze", likes: "956" },
  { id: 5, image: "/catalog/kurta.png", author: "@wedding_diaries", likes: "1.5k" },
  { id: 6, image: "/catalog/casual-shirt.png", author: "@hypebeast99", likes: "3.2k" },
  { id: 7, image: "/catalog/blazer.png", author: "@styled_by_ai", likes: "402" },
  { id: 8, image: "/catalog/hoodie.png", author: "@cozy_fits", likes: "5.5k" },
];

export default function ExplorePage() {
  const { status } = useSession();
  const isLoadingSession = status === "loading";
  const router = useRouter();

  const handleTryStyle = (e, url) => {
    e.preventDefault();
    router.push(`/?outfitUrl=${encodeURIComponent(url)}`);
  };

  return (
    <>
      <LoadingOverlay isVisible={isLoadingSession} />
      <div className={styles.container}>
        <div className={styles.header}>
          <div className={styles.titleWrapper}>
            <h1 className={styles.title}>Community Explore</h1>
            <span className={styles.pulseDot}></span>
          </div>
          <p className={styles.subtitle}>
            Discover over 500,000+ AI styled outfits generated by the FitSnap community today. Found a look you love? Try it on yourself instantly.
          </p>
        </div>

        {/* Masonry-style Grid */}
        <div className={styles.masonryGrid}>
          {EXPLORE_FEED.map((post) => (
            <div key={post.id} className={styles.postCard}>
              <Image 
                src={post.image} 
                alt="Community Generation" 
                className={styles.image} 
                fill
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                priority={post.id <= 4}
              />
              
              <div className={styles.overlay}>
                <div className={styles.statsRow}>
                  <div className={styles.authorBadge}>
                    <div className={styles.authorAvatar} />
                    <span>{post.author}</span>
                  </div>
                  <div className={styles.likes}>
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" stroke="none">
                      <path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/>
                    </svg>
                    {post.likes}
                  </div>
                </div>

                <button className={styles.tryBtn} onClick={(e) => handleTryStyle(e, post.image)}>
                  Try This Style ✨
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}
